name: embedanythingindart
description: A wrapper for the popular embedanything rust crate
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.0

dev_dependencies:
  hooks: ^1.0.0
  lints: ^6.0.0
  native_toolchain_rust: ^1.0.0
  test: ^1.25.6
