[toolchain]
channel = "1.90.0"
components = ["rustfmt", "clippy"]
targets = [
    # macOS
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    # Linux
    "x86_64-unknown-linux-gnu",
    # Windows
    "x86_64-pc-windows-msvc",
]
